# Generated by Django 4.2.5 on 2023-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIrst_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Skills', models.CharField(max_length=50)),
                ('Experience', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Company', models.CharField(max_length=50)),
            ],
        ),
    ]
